"""deleted room table

Revision ID: 3563b99cade4
Revises: 
Create Date: 2026-09-14 17:12:16.215013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3563b99cade4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('roomcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('room_host_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_pkey'))
    )
    # ### end Alembic commands ###
