"""removed role and is_alive from RoomPlayer table

Revision ID: b16d9d66963d
Revises: 3563b99cade4
Create Date: 2026-09-15 12:23:31.385995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16d9d66963d'
down_revision: Union[str, Sequence[str], None] = '3563b99cade4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'room_player', ['room_id', 'user_id'])
    op.drop_column('room_player', 'role')
    op.drop_column('room_player', 'is_alive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_player', sa.Column('is_alive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room_player', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'room_player', type_='unique')
    # ### end Alembic commands ###
