"""added_voting_attempt column to game and game action

Revision ID: d225a297bc45
Revises: b16d9d66963d
Create Date: 2026-09-17 00:58:51.672924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd225a297bc45'
down_revision: Union[str, Sequence[str], None] = 'b16d9d66963d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('voting_attempt', sa.Integer(), nullable=True))
    op.add_column('game_action', sa.Column('voting_attempt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_action', 'voting_attempt')
    op.drop_column('game', 'voting_attempt')
    # ### end Alembic commands ###
